---
- name: variable playbook test
  hosts: localhost
  gather_facts: no
  
  vars:
    var_1: awesome
    var_2: ansible is
    var_3: "{{ var_2 }} {{ var_1 }}"
    
  tasks:
  
    - name: print {{ var_3 }}
      debug:
        msg: "{{ var_3 }}"
